# Generated by Django 5.2.3 on 2025-06-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiceover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='voiceovers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
