# Generated by Django 5.2.3 on 2025-06-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_alter_voiceover_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceover',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='audio_file',
            field=models.FileField(upload_to='voiceover/'),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
