# Generated by Django 5.2.3 on 2025-06-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_voiceover_deleted_alter_voiceover_audio_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceover',
            name='deleted',
        ),
    ]
